[sensors.humidity]
platform="sensor"
device_class="humidity"
icon="mdi:water-percent"
unit="%"

[sensors.humidityin]
name="humidity_indoor"
platform="sensor"
device_class="humidity"
icon="mdi:water-percent"
unit="%"

[sensors.tempf]
name="temp"
platform="sensor"
device_class="temperature"
icon="mdi:thermometer-lines"
unit_class="temperature"
unit="°F"

[sensors.tempinf]
name="temp_indoor"
platform="sensor"
device_class="temperature"
icon="mdi:thermometer-lines"
unit_class="temperature"
unit="°F"

# status of backup battery for CO2 sensor
# 1 = Good
# 0 = Bad
# NOTE: This gets reported even on some devices without a CO2 sensor
[sensors.batt_co2]
name="batt_co2"
platform="binary_sensor"
device_class="battery"
icon="mdi:battery"

# status of backup battery for outdoor sensor
# 1 = Good
# 0 = Bad
[sensors.battout]
name="backup_battery"
platform="binary_sensor"
device_class="battery"
icon="mdi:battery"

[sensors.baromabsin]
name="barometer_absolute"
platform="sensor"
device_class="pressure"
unit="inHg"

[sensors.baromrelin]
name="barometer_relative"
platform="sensor"
device_class="pressure"
unit="inHg"

[sensors.winddir]
name="wind_direction"
platform="sensor"
icon="mdi:weather-windy"
unit="°"

[sensors.maxdailygust]
name="max_daily_wind_gust"
platform="sensor"
icon="mdi:weather-windy"
unit="mph"

[sensors.windgustmph]
name="wind_gust"
platform="sensor"
icon="mdi:weather-windy"
unit="mph"

[sensors.windspeedmph]
name="wind_speed"
platform="sensor"
icon="mdi:weather-windy"
unit="mph"

[sensors.monthlyrainin]
name="monthly_rain"
platform="sensor"
icon="mdi:water"
unit="in"

[sensors.weeklyrainin]
name="weekly_rain"
platform="sensor"
icon="mdi:water"
unit="in"

[sensors.dailyrainin]
name="daily_rain"
platform="sensor"
icon="mdi:water"
unit="in"

[sensors.eventrainin]
name="event_rain"
platform="sensor"
icon="mdi:water"
unit="in"

[sensors.hourlyrainin]
name="hourly_rain"
platform="sensor"
icon="mdi:water"
unit="in"

[sensors.totalrainin]
name="total_rain"
platform="sensor"
icon="mdi:water"
unit="in"

[sensors.solarradiation]
name="solar_radiation"
platform="sensor"
device_class="illuminance"
unit="W/m^2"

[sensors.uv]
name="uv_index"
platform="sensor"
device_class="illuminance"
icon="mdi:weather-sunny"
unit="index"
